# Generated by Django 4.2.6 on 2023-10-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capteur',
            name='humidite',
        ),
    ]
