# Generated by Django 4.2.6 on 2023-10-31 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_remove_capteur_humidite'),
    ]

    operations = [
        migrations.AddField(
            model_name='capteur',
            name='nomCapteur',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capteur',
            name='nomUc',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
